plugins {
	id 'java'
	id 'org.springframework.boot' version '3.3.10'
	id 'io.spring.dependency-management' version '1.1.7'
}

group = 'com.practice'
version = '0.0.1-SNAPSHOT'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(17)
	}
}

configurations {
	compileOnly {
		extendsFrom annotationProcessor
	}
}

repositories {
	mavenCentral()
}

dependencies {
	implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
	implementation 'org.springframework.boot:spring-boot-starter-web'
	compileOnly 'org.projectlombok:lombok'
	runtimeOnly 'com.mysql:mysql-connector-j'
	annotationProcessor 'org.projectlombok:lombok'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
	implementation 'org.springframework.boot:spring-boot-starter-validation'
	// redis
	implementation 'org.springframework.boot:spring-boot-starter-data-redis'
	// Mongo DB
	implementation 'org.springframework.boot:spring-boot-starter-data-mongodb'
	// Test
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
	// h2
	testRuntimeOnly 'com.h2database:h2'
    /* jwt */
    implementation 'io.jsonwebtoken:jjwt:0.12.6'
    implementation 'javax.xml.bind:jaxb-api:2.3.1'
    /* OAuth2 */
    implementation 'org.springframework.boot:spring-boot-starter-oauth2-client'
}

tasks.named('test') {
	useJUnitPlatform()
    jvmArgs "-Xshare:off"
}
